"""
Meta Graph API service layer — Phase A2.

Responsibilities:
  - Build the Facebook OAuth 2.0 authorization URL.
  - Exchange an OAuth authorization code for a short-lived user access token.
  - Upgrade a short-lived token to a long-lived token (60-day expiry).
  - Fetch all Facebook Pages the user manages (with page-level access tokens).
  - Debug / inspect a token (used for health checks).

Design decisions:
  - Async httpx.AsyncClient is used for all HTTP calls. A single client is
    shared per-request via dependency injection or direct call; it is NOT
    held as a module-level singleton because each OAuth flow is a one-shot
    operation and we want explicit connection lifecycle control.
  - All Graph API version references are pinned via GRAPH_VERSION so a
    single constant controls upgrade.
  - Errors from Meta are surfaced as HTTPException so FastAPI returns a
    consistent JSON error response to the frontend.
  - This module is deliberately free of SQLAlchemy / DB concerns. The
    endpoint layer handles persistence.
"""

import logging
from dataclasses import dataclass
from urllib.parse import urlencode

import httpx
from fastapi import HTTPException, status

from app.core.config import settings

logger = logging.getLogger(__name__)

# ── Constants ──────────────────────────────────────────────────────────────────
GRAPH_VERSION = "v20.0"
GRAPH_BASE = f"https://graph.facebook.com/{GRAPH_VERSION}"
DIALOG_BASE = "https://www.facebook.com/{version}/dialog/oauth".format(
    version=GRAPH_VERSION
)

# Permissions the merchant must grant so the bot can read & reply
OAUTH_SCOPES = ",".join([
    "pages_messaging",
    "pages_manage_metadata",
    "pages_read_engagement",
    "pages_manage_engagement",
    "pages_show_list",
])


# ── Data shapes ────────────────────────────────────────────────────────────────

@dataclass
class PageData:
    """Normalized representation of a Facebook Page from /me/accounts."""
    page_id: str
    page_name: str
    access_token: str   # plain-text page access token — caller must encrypt


# ── Helpers ────────────────────────────────────────────────────────────────────

def _callback_uri() -> str:
    """Canonical redirect URI registered in the Meta App Dashboard."""
    return f"{settings.BACKEND_URL}/api/v1/fb/callback"


def _raise_for_meta_error(response: httpx.Response, context: str) -> None:
    """
    Parse Meta Graph API error envelope and surface it as an HTTPException.

    Meta always returns errors as:
      {"error": {"message": "...", "type": "...", "code": ..., ...}}
    """
    try:
        data = response.json()
    except Exception:
        response.raise_for_status()
        return

    if "error" in data:
        err = data["error"]
        msg = err.get("message", "Unknown Meta API error")
        code = err.get("code", 0)
        logger.error("[Meta API] %s failed — code=%s msg=%s", context, code, msg)
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"Meta API error during {context}: {msg}",
        )


# ── Public API ─────────────────────────────────────────────────────────────────

def build_oauth_url(state: str) -> str:
    """
    Build the Facebook OAuth dialog URL.

    Args:
        state: CSRF-protection token (JWT-signed, contains org_id + expiry).
               Generated by the endpoint layer.

    Returns:
        Full URL to redirect the merchant's browser to.
    """
    params = {
        "client_id": settings.META_APP_ID,
        "redirect_uri": _callback_uri(),
        "scope": OAUTH_SCOPES,
        "response_type": "code",
        "state": state,
    }
    return f"{DIALOG_BASE}?{urlencode(params)}"


async def exchange_code_for_user_token(code: str) -> str:
    """
    Exchange the authorization code (from the OAuth callback) for a
    short-lived user access token.

    Meta endpoint: GET /oauth/access_token
    """
    async with httpx.AsyncClient(timeout=15.0) as client:
        response = await client.get(
            f"{GRAPH_BASE}/oauth/access_token",
            params={
                "client_id": settings.META_APP_ID,
                "client_secret": settings.META_APP_SECRET,
                "redirect_uri": _callback_uri(),
                "code": code,
            },
        )
        _raise_for_meta_error(response, "code→token exchange")
        data = response.json()
        token = data.get("access_token")
        if not token:
            raise HTTPException(
                status_code=status.HTTP_502_BAD_GATEWAY,
                detail="Meta did not return an access token.",
            )
        logger.info("Short-lived user token obtained successfully.")
        return token


async def upgrade_to_long_lived_token(short_lived_token: str) -> str:
    """
    Exchange a short-lived user token (1-2 hours) for a long-lived token
    (~60 days). Long-lived tokens should be used to obtain permanent Page
    Access Tokens via /me/accounts.

    Meta endpoint: GET /oauth/access_token?grant_type=fb_exchange_token
    """
    async with httpx.AsyncClient(timeout=15.0) as client:
        response = await client.get(
            f"{GRAPH_BASE}/oauth/access_token",
            params={
                "grant_type": "fb_exchange_token",
                "client_id": settings.META_APP_ID,
                "client_secret": settings.META_APP_SECRET,
                "fb_exchange_token": short_lived_token,
            },
        )
        _raise_for_meta_error(response, "token upgrade")
        data = response.json()
        long_lived = data.get("access_token")
        if not long_lived:
            raise HTTPException(
                status_code=status.HTTP_502_BAD_GATEWAY,
                detail="Meta did not return a long-lived token.",
            )
        logger.info("Long-lived user token obtained. Expires in ~60 days.")
        return long_lived


async def get_managed_pages(user_token: str) -> list[PageData]:
    """
    Fetch all Facebook Pages the authenticated user manages, along with
    their individual Page Access Tokens.

    Page Access Tokens obtained via /me/accounts with a long-lived user
    token are permanent (no expiry) unless the user revokes permissions.

    Meta endpoint: GET /me/accounts
    """
    async with httpx.AsyncClient(timeout=15.0) as client:
        response = await client.get(
            f"{GRAPH_BASE}/me/accounts",
            params={
                "access_token": user_token,
                "fields": "id,name,access_token",
            },
        )
        _raise_for_meta_error(response, "fetch managed pages")
        data = response.json()

    pages = []
    for page in data.get("data", []):
        if not page.get("access_token"):
            logger.warning("Page %s has no access token — skipping.", page.get("id"))
            continue
        pages.append(PageData(
            page_id=page["id"],
            page_name=page.get("name", ""),
            access_token=page["access_token"],
        ))

    logger.info("Retrieved %d managed page(s) from Meta.", len(pages))
    return pages


async def debug_token(token: str) -> dict:
    """
    Inspect a token's validity, expiry, and granted scopes via the
    Graph API debug_token endpoint. Useful for health checks.

    Returns raw Meta response dict.
    """
    app_token = f"{settings.META_APP_ID}|{settings.META_APP_SECRET}"
    async with httpx.AsyncClient(timeout=10.0) as client:
        response = await client.get(
            f"{GRAPH_BASE}/debug_token",
            params={"input_token": token, "access_token": app_token},
        )
        _raise_for_meta_error(response, "debug token")
        return response.json().get("data", {})
